# Generated by Django 6.0.3 on 2026-03-22 00:52

from django.db import migrations


CATEGORIES = [
    # Ingresos
    {"name": "Salario",         "icon": "💰", "color": "#22C55E", "type": "income"},
    {"name": "Freelance",       "icon": "💻", "color": "#10B981", "type": "income"},
    {"name": "Inversiones",     "icon": "📈", "color": "#06B6D4", "type": "income"},
    {"name": "Regalo",          "icon": "🎁", "color": "#8B5CF6", "type": "income"},
    # Egresos
    {"name": "Alimentación",    "icon": "🍔", "color": "#EF4444", "type": "expense"},
    {"name": "Transporte",      "icon": "🚗", "color": "#F97316", "type": "expense"},
    {"name": "Renta",           "icon": "🏠", "color": "#F59E0B", "type": "expense"},
    {"name": "Salud",           "icon": "💊", "color": "#EC4899", "type": "expense"},
    {"name": "Entretenimiento", "icon": "🎮", "color": "#A855F7", "type": "expense"},
    {"name": "Ropa",            "icon": "👕", "color": "#6366F1", "type": "expense"},
    {"name": "Educación",       "icon": "📚", "color": "#3B82F6", "type": "expense"},
    {"name": "Servicios",       "icon": "⚡", "color": "#14B8A6", "type": "expense"},
    {"name": "Supermercado",    "icon": "🛒", "color": "#84CC16", "type": "expense"},
    {"name": "Otros",           "icon": "📌", "color": "#6B7280", "type": "expense"},
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("api", "Category")
    for cat in CATEGORIES:
        Category.objects.get_or_create(name=cat["name"], defaults={
            "icon": cat["icon"],
            "color": cat["color"],
            "type": cat["type"],
        })


def delete_default_categories(apps, schema_editor):
    Category = apps.get_model("api", "Category")
    names = [c["name"] for c in CATEGORIES]
    Category.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_category_transaction"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, delete_default_categories),
    ]
