# Generated by Django 6.0.3 on 2026-04-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('ultimos_4', models.CharField(blank=True, default='', max_length=4)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('limite_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('corte_dia', models.PositiveSmallIntegerField()),
                ('pago_dia', models.PositiveSmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('minimo', 'Pago mínimo'), ('total', 'Pago total'), ('parcial', 'Pago parcial')], default='total', max_length=10)),
                ('pago_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.creditcard')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CardExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_msi', models.BooleanField(default=False)),
                ('meses', models.PositiveSmallIntegerField(default=1)),
                ('pagado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.creditcard')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
