# Generated by Django 6.0.3 on 2026-04-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cardexpense_mes_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('fecha_pago_limite', models.DateField()),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mensualidades', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pago_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado — pendiente de pago'), ('pagado', 'Pagado')], default='abierto', max_length=10)),
                ('pagado_en', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas_pago', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.creditcard')),
            ],
            options={
                'ordering': ['-fin'],
            },
        ),
    ]
