# Generated by Django 6.0.3 on 2026-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cardstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardstatement',
            name='saldo_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
